# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('a_by', models.CharField(max_length=30)),
                ('a_content', models.CharField(max_length=1000)),
                ('a_upvotes', models.IntegerField(default=0)),
                ('a_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('c_parID', models.CharField(max_length=20)),
                ('c_time', models.TimeField(auto_now_add=True)),
                ('c_by', models.CharField(max_length=30)),
                ('c_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('q_des', models.CharField(max_length=1000)),
                ('q_tag', models.CharField(max_length=30)),
                ('q_by', models.CharField(max_length=30)),
                ('q_upvotes', models.IntegerField(default=0)),
                ('q_views', models.IntegerField(default=0)),
                ('q_time', models.TimeField(auto_now_add=True)),
                ('q_acount', models.IntegerField(default=0)),
                ('q_reports', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('q_count', models.IntegerField(default=0)),
                ('a_count', models.IntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='a_qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Questions'),
        ),
    ]
